### ISSUE TITLE
atomic asset generator

### ISSUE THREAD

**Issue by bbrock25** [spartansystems/atomic_assets#4]
When creating a new atomic asset, the developer should be able to run 
``` 
rails g atomic_assets:component component_name 
```

and have the associated files created for them
* [ ] component_name.rb
* [ ] component_name.scss
* [ ] component_name.js
* [ ] component_name.html.slim

**Comment by bbrock25** [comment]
picking this one up.

**Comment by squaresurf** [comment]
Why was this closed? Is there a PR that can be linked? None of the checklists are marked off.

**Comment by bbrock25** [comment]
It was addressed by this [commit](https://github.com/spartansystems/atomic_assets/commit/62b8587b329c4c53a2aa3ca9b834805918e36179)

**Comment by squaresurf** [comment]
For future reference it was PR #5
